version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: "consensus"
      POSTGRES_USER: "akrik"
      POSTGRES_PASSWORD: "akrik"
    ports:
      - "5432:5432"

  mysql:
    container_name: mysql_container
    restart: always
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: consensus
      MYSQL_USER: akrik
      MYSQL_PASSWORD: akrik
      MYSQL_ROOT_PASSWORD: akrik
    ports:
      - "3306:3306"